ARG ARG_VERSION=local

FROM ghcr.io/jaime-project/jaime-agent:${ARG_VERSION}

ENV AGENT_TYPE=OPENSHIFT

COPY resources/oc.tar.gz . 
RUN tar -xf oc.tar.gz 
RUN rm oc.tar.gz

RUN chmod 755 oc
ENV PATH="$HOME:$PATH"
