ARG ARG_VERSION=local

FROM ghcr.io/jaime-project/jaime-agent:${ARG_VERSION}

ENV AGENT_TYPE=PUSHGATEWAY

USER root

ADD resources/pushgateway.tar.gz .
RUN mv pushgateway /usr/local/bin/

USER 1001

ENV EXTRA_CMD="pushgateway"
EXPOSE 9091