FROM brianwolf94/jaime-agent:1.5.0

ENV AGENT_TYPE=PUSHGATEWAY

RUN wget https://github.com/prometheus/pushgateway/releases/download/v1.2.0/pushgateway-1.2.0.linux-amd64.tar.gz
RUN tar xvfz pushgateway-1.2.0.linux-amd64.tar.gz
RUN cp pushgateway-1.2.0.linux-amd64/pushgateway /usr/local/bin/

CMD gunicorn -b ${PYTHON_HOST}:${PYTHON_PORT} --workers=1 --threads=4 app:app & /usr/local/bin/pushgateway
# CMD systectl start & /usr/local/bin/pushgateway