FROM brianwolf94/jaime-agent:1.5.0

ENV AGENT_TYPE=OPENSHIFT

COPY resources/oc.tar.gz . 
RUN tar -xf oc.tar.gz -C /usr/local/bin/
RUN rm oc.tar.gz

ENV EXTRA_CMD="echo 'ASDADASDAS' > /tmp/prueba.txt"

