FROM brianwolf94/jaime-agent:1.6.2

ENV AGENT_TYPE=PUSHGATEWAY

RUN wget https://github.com/prometheus/pushgateway/releases/download/v1.2.0/pushgateway-1.2.0.linux-amd64.tar.gz
RUN tar xvfz pushgateway-1.2.0.linux-amd64.tar.gz
RUN rm -fr pushgateway-1.2.0.linux-amd64.tar.gz

RUN chmod 755 pushgateway-1.2.0.linux-amd64 -R
ENV PATH="$HOME/pushgateway-1.2.0.linux-amd64:$PATH"

ENV EXTRA_CMD="pushgateway"
EXPOSE 9091