FROM ghcr.io/jaime-project/jaime-agent:latest

ENV AGENT_TYPE=KUBERNETES

COPY resources/kubectl.tar.gz . 
RUN tar -xf kubectl.tar.gz 
RUN rm kubectl.tar.gz

RUN chmod 755 kubectl
ENV PATH="$HOME:$PATH"
