name: cicd

on:
  push:
    tags:
      - "*"
      
jobs:

  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create-version
      id: create-version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
    - name: show-version
      run: echo "Version to build -> ${{ steps.create-version.outputs.version }}"
    outputs:
      version: ${{ steps.create-version.outputs.version }}
  

  build-and-push-base:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
      
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    

    - name: Log in to registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.PERSONAL_TOKEN }}" | docker login ghcr.io -u pcastelo --password-stdin
      
      
    - name: print token
      run: echo "${{ secrets.PERSONAL_TOKEN }}"
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: ghcr.io/jaime-project/project-jaime-agent/jaime-agent:${{ needs.get-version.outputs.version }}
        platforms: linux/amd64
        build-args: ARG_VERSION=${{ needs.get-version.outputs.version }}
    outputs:
      version: ${{ needs.get-version.outputs.version }}
  
