name: cicd

on:
  push:
    tags:
      - "*"
      
jobs:

  get-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create-version
      id: create-version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
    - name: show-version
      run: echo "Version to build -> ${{ steps.create-version.outputs.version }}"
    outputs:
      version: ${{ steps.create-version.outputs.version }}
  build-and-push-base:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v3 
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2  
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   
    - name: Build and push base
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: ghcr.io/jaime-project/${{ secrets.APP_NAME }}:${{ needs.get-version.outputs.version }} 
        platforms: linux/amd64
        build-args: ARG_VERSION=${{ needs.get-version.outputs.version }}
    - name: Build and push cluster
      id: docker_build_k8s
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile.cluster
        tags: ghcr.io/jaime-project/${{ secrets.APP_NAME }}-cluster:${{ needs.get-version.outputs.version }} 
        platforms: linux/amd64
        build-args: ARG_VERSION=${{ needs.get-version.outputs.version }}
    - name: Build and push pushgateway
      id: docker_build_pushgateway
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./
        file: ./Dockerfile.pushgateway
        tags: ghcr.io/jaime-project/${{ secrets.APP_NAME }}-pushgateway:${{ needs.get-version.outputs.version }} 
        platforms: linux/amd64
        build-args: ARG_VERSION=${{ needs.get-version.outputs.version }}            
    outputs:
      version: ${{ needs.get-version.outputs.version }}
  
