name: release
on:
  push:
    branches: [master]     
jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3     
    - name: Release to GitHub
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      with:
        extra_plugins: |
          conventional-changelog-conventionalcommits       
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
    - name: Do something when a new release published
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
    outputs:
      version: ${{ steps.semantic.outputs.new_release_version }}
        
